// export { default as Header } from './Header'
export { default as Body } from './Body'
export { default as Footer } from './Footer'

export { default as Admin } from './Body/Admin'
export { default as Home } from './Body/Home'
export { default as Contact } from './Body/Contact'
export { default as Member } from './Body/Member'
export { default as Menu } from './Body/Menu'
export { default as News } from './Body/News'
